const hiraganaData = [
  { char: "あ", romaji: "a", group: "a-row" },
  { char: "い", romaji: "i", group: "a-row" },
  { char: "う", romaji: "u", group: "a-row" },
  { char: "え", romaji: "e", group: "a-row" },
  { char: "お", romaji: "o", group: "a-row" },
  { char: "か", romaji: "ka", group: "ka-row" },
  { char: "き", romaji: "ki", group: "ka-row" },
  { char: "く", romaji: "ku", group: "ka-row" },
  { char: "け", romaji: "ke", group: "ka-row" },
  { char: "こ", romaji: "ko", group: "ka-row" },
  { char: "さ", romaji: "sa", group: "sa-row" },
  { char: "し", romaji: "shi", group: "sa-row" },
  { char: "す", romaji: "su", group: "sa-row" },
  { char: "せ", romaji: "se", group: "sa-row" },
  { char: "そ", romaji: "so", group: "sa-row" },
  { char: "た", romaji: "ta", group: "ta-row" },
  { char: "ち", romaji: "chi", group: "ta-row" },
  { char: "つ", romaji: "tsu", group: "ta-row" },
  { char: "て", romaji: "te", group: "ta-row" },
  { char: "と", romaji: "to", group: "ta-row" },
  { char: "な", romaji: "na", group: "na-row" },
  { char: "に", romaji: "ni", group: "na-row" },
  { char: "ぬ", romaji: "nu", group: "na-row" },
  { char: "ね", romaji: "ne", group: "na-row" },
  { char: "の", romaji: "no", group: "na-row" },
  { char: "は", romaji: "ha", group: "ha-row" },
  { char: "ひ", romaji: "hi", group: "ha-row" },
  { char: "ふ", romaji: "fu", group: "ha-row" },
  { char: "へ", romaji: "he", group: "ha-row" },
  { char: "ほ", romaji: "ho", group: "ha-row" },
  { char: "ま", romaji: "ma", group: "ma-row" },
  { char: "み", romaji: "mi", group: "ma-row" },
  { char: "む", romaji: "mu", group: "ma-row" },
  { char: "め", romaji: "me", group: "ma-row" },
  { char: "も", romaji: "mo", group: "ma-row" },
  { char: "や", romaji: "ya", group: "ya-row" },
  { char: "ゆ", romaji: "yu", group: "ya-row" },
  { char: "よ", romaji: "yo", group: "ya-row" },
  { char: "ら", romaji: "ra", group: "ra-row" },
  { char: "り", romaji: "ri", group: "ra-row" },
  { char: "る", romaji: "ru", group: "ra-row" },
  { char: "れ", romaji: "re", group: "ra-row" },
  { char: "ろ", romaji: "ro", group: "ra-row" },
  { char: "わ", romaji: "wa", group: "wa-row" },
  { char: "を", romaji: "wo", group: "wa-row" },
  { char: "ん", romaji: "n", group: "n-row" },
  { char: "が", romaji: "ga", group: "ga-row" },
  { char: "ぎ", romaji: "gi", group: "ga-row" },
  { char: "ぐ", romaji: "gu", group: "ga-row" },
  { char: "げ", romaji: "ge", group: "ga-row" },
  { char: "ご", romaji: "go", group: "ga-row" },
  { char: "ざ", romaji: "za", group: "za-row" },
  { char: "じ", romaji: "ji", group: "za-row" },
  { char: "ず", romaji: "zu", group: "za-row" },
  { char: "ぜ", romaji: "ze", group: "za-row" },
  { char: "ぞ", romaji: "zo", group: "za-row" },
  { char: "だ", romaji: "da", group: "da-row" },
  { char: "ぢ", romaji: "ji", group: "da-row" },
  { char: "づ", romaji: "zu", group: "da-row" },
  { char: "で", romaji: "de", group: "da-row" },
  { char: "ど", romaji: "do", group: "da-row" },
  { char: "ば", romaji: "ba", group: "ba-row" },
  { char: "び", romaji: "bi", group: "ba-row" },
  { char: "ぶ", romaji: "bu", group: "ba-row" },
  { char: "べ", romaji: "be", group: "ba-row" },
  { char: "ぼ", romaji: "bo", group: "ba-row" },
  { char: "ぱ", romaji: "pa", group: "pa-row" },
  { char: "ぴ", romaji: "pi", group: "pa-row" },
  { char: "ぷ", romaji: "pu", group: "pa-row" },
  { char: "ぺ", romaji: "pe", group: "pa-row" },
  { char: "ぽ", romaji: "po", group: "pa-row" }
];

const katakanaData = [
  { char: "ア", romaji: "a", group: "a-row" },
  { char: "イ", romaji: "i", group: "a-row" },
  { char: "ウ", romaji: "u", group: "a-row" },
  { char: "エ", romaji: "e", group: "a-row" },
  { char: "オ", romaji: "o", group: "a-row" },
  { char: "カ", romaji: "ka", group: "ka-row" },
  { char: "キ", romaji: "ki", group: "ka-row" },
  { char: "ク", romaji: "ku", group: "ka-row" },
  { char: "ケ", romaji: "ke", group: "ka-row" },
  { char: "コ", romaji: "ko", group: "ka-row" },
  { char: "サ", romaji: "sa", group: "sa-row" },
  { char: "シ", romaji: "shi", group: "sa-row" },
  { char: "ス", romaji: "su", group: "sa-row" },
  { char: "セ", romaji: "se", group: "sa-row" },
  { char: "ソ", romaji: "so", group: "sa-row" },
  { char: "タ", romaji: "ta", group: "ta-row" },
  { char: "チ", romaji: "chi", group: "ta-row" },
  { char: "ツ", romaji: "tsu", group: "ta-row" },
  { char: "テ", romaji: "te", group: "ta-row" },
  { char: "ト", romaji: "to", group: "ta-row" },
  { char: "ナ", romaji: "na", group: "na-row" },
  { char: "ニ", romaji: "ni", group: "na-row" },
  { char: "ヌ", romaji: "nu", group: "na-row" },
  { char: "ネ", romaji: "ne", group: "na-row" },
  { char: "ノ", romaji: "no", group: "na-row" },
  { char: "ハ", romaji: "ha", group: "ha-row" },
  { char: "ヒ", romaji: "hi", group: "ha-row" },
  { char: "フ", romaji: "fu", group: "ha-row" },
  { char: "ヘ", romaji: "he", group: "ha-row" },
  { char: "ホ", romaji: "ho", group: "ha-row" },
  { char: "マ", romaji: "ma", group: "ma-row" },
  { char: "ミ", romaji: "mi", group: "ma-row" },
  { char: "ム", romaji: "mu", group: "ma-row" },
  { char: "メ", romaji: "me", group: "ma-row" },
  { char: "モ", romaji: "mo", group: "ma-row" },
  { char: "ヤ", romaji: "ya", group: "ya-row" },
  { char: "ユ", romaji: "yu", group: "ya-row" },
  { char: "ヨ", romaji: "yo", group: "ya-row" },
  { char: "ラ", romaji: "ra", group: "ra-row" },
  { char: "リ", romaji: "ri", group: "ra-row" },
  { char: "ル", romaji: "ru", group: "ra-row" },
  { char: "レ", romaji: "re", group: "ra-row" },
  { char: "ロ", romaji: "ro", group: "ra-row" },
  { char: "ワ", romaji: "wa", group: "wa-row" },
  { char: "ヲ", romaji: "wo", group: "wa-row" },
  { char: "ン", romaji: "n", group: "n-row" },
  { char: "ガ", romaji: "ga", group: "ga-row" },
  { char: "ギ", romaji: "gi", group: "ga-row" },
  { char: "グ", romaji: "gu", group: "ga-row" },
  { char: "ゲ", romaji: "ge", group: "ga-row" },
  { char: "ゴ", romaji: "go", group: "ga-row" },
  { char: "ザ", romaji: "za", group: "za-row" },
  { char: "ジ", romaji: "ji", group: "za-row" },
  { char: "ズ", romaji: "zu", group: "za-row" },
  { char: "ゼ", romaji: "ze", group: "za-row" },
  { char: "ゾ", romaji: "zo", group: "za-row" },
  { char: "ダ", romaji: "da", group: "da-row" },
  { char: "ヂ", romaji: "ji", group: "da-row" },
  { char: "ヅ", romaji: "zu", group: "da-row" },
  { char: "デ", romaji: "de", group: "da-row" },
  { char: "ド", romaji: "do", group: "da-row" },
  { char: "バ", romaji: "ba", group: "ba-row" },
  { char: "ビ", romaji: "bi", group: "ba-row" },
  { char: "ブ", romaji: "bu", group: "ba-row" },
  { char: "ベ", romaji: "be", group: "ba-row" },
  { char: "ボ", romaji: "bo", group: "ba-row" },
  { char: "パ", romaji: "pa", group: "pa-row" },
  { char: "ピ", romaji: "pi", group: "pa-row" },
  { char: "プ", romaji: "pu", group: "pa-row" },
  { char: "ペ", romaji: "pe", group: "pa-row" },
  { char: "ポ", romaji: "po", group: "pa-row" }
];

const kanjiData = [
  { char: "一", romaji: "ichi", meaning: "one" },
  { char: "二", romaji: "ni", meaning: "two" },
  { char: "三", romaji: "san", meaning: "three" },
  { char: "四", romaji: "shi / yon", meaning: "four" },
  { char: "五", romaji: "go", meaning: "five" },
  { char: "六", romaji: "roku", meaning: "six" },
  { char: "七", romaji: "shichi / nana", meaning: "seven" },
  { char: "八", romaji: "hachi", meaning: "eight" },
  { char: "九", romaji: "kyuu / ku", meaning: "nine" },
  { char: "十", romaji: "juu", meaning: "ten" },
  { char: "百", romaji: "hyaku", meaning: "hundred" },
  { char: "千", romaji: "sen", meaning: "thousand" },
  { char: "万", romaji: "man", meaning: "ten thousand" },
  { char: "円", romaji: "en", meaning: "circle / yen" },
  { char: "日", romaji: "nichi / hi", meaning: "day / sun" },
  { char: "月", romaji: "getsu / tsuki", meaning: "month / moon" },
  { char: "火", romaji: "ka / hi", meaning: "fire" },
  { char: "水", romaji: "sui / mizu", meaning: "water" },
  { char: "木", romaji: "moku / ki", meaning: "tree / wood" },
  { char: "金", romaji: "kin / kane", meaning: "gold / money" },
  { char: "土", romaji: "do / tsuchi", meaning: "earth / soil" },
  { char: "曜", romaji: "you", meaning: "day of week" },
  { char: "年", romaji: "nen / toshi", meaning: "year" },
  { char: "時", romaji: "ji / toki", meaning: "time / hour" },
  { char: "分", romaji: "bun / pun", meaning: "minute / part" },
  { char: "半", romaji: "han", meaning: "half" },
  { char: "上", romaji: "jou / ue", meaning: "above / up" },
  { char: "下", romaji: "ka / shita", meaning: "below / down" },
  { char: "中", romaji: "chuu / naka", meaning: "inside / middle" },
  { char: "大", romaji: "dai / ookii", meaning: "big / large" },
  { char: "小", romaji: "shou / chiisai", meaning: "small / little" },
  { char: "左", romaji: "sa / hidari", meaning: "left" },
  { char: "右", romaji: "u / migi", meaning: "right" },
  { char: "前", romaji: "zen / mae", meaning: "before / front" },
  { char: "後", romaji: "go / ushiro", meaning: "after / behind" },
  { char: "内", romaji: "nai / uchi", meaning: "inside" },
  { char: "外", romaji: "gai / soto", meaning: "outside" },
  { char: "北", romaji: "kita", meaning: "north" },
  { char: "南", romaji: "minami", meaning: "south" },
  { char: "東", romaji: "tou / higashi", meaning: "east" },
  { char: "西", romaji: "sei / nishi", meaning: "west" },
  { char: "入", romaji: "nyuu / hairu", meaning: "enter" },
  { char: "出", romaji: "shutsu / deru", meaning: "exit / leave" },
  { char: "立", romaji: "ritsu / tatsu", meaning: "stand" },
  { char: "休", romaji: "kyuu / yasumu", meaning: "rest" },
  { char: "先", romaji: "sen / saki", meaning: "previous / ahead" },
  { char: "生", romaji: "sei / ikiru", meaning: "life / birth" },
  { char: "学", romaji: "gaku / manabu", meaning: "study / learn" },
  { char: "校", romaji: "kou", meaning: "school" },
  { char: "国", romaji: "koku / kuni", meaning: "country" },
  { char: "語", romaji: "go / kata", meaning: "language" },
  { char: "文", romaji: "bun / fumi", meaning: "writing / sentence" },
  { char: "字", romaji: "ji", meaning: "character / letter" },
  { char: "本", romaji: "hon / moto", meaning: "book / origin" },
  { char: "名", romaji: "mei / na", meaning: "name" },
  { char: "人", romaji: "jin / hito", meaning: "person" },
  { char: "子", romaji: "shi / ko", meaning: "child" },
  { char: "男", romaji: "dan / otoko", meaning: "man / male" },
  { char: "女", romaji: "jo / onna", meaning: "woman / female" },
  { char: "父", romaji: "fu / chichi", meaning: "father" },
  { char: "母", romaji: "bo / haha", meaning: "mother" },
  { char: "友", romaji: "yuu / tomo", meaning: "friend" },
  { char: "私", romaji: "shi / watashi", meaning: "I / me" },
  { char: "今", romaji: "kon / ima", meaning: "now" },
  { char: "何", romaji: "ka / nani", meaning: "what / how many" },
  { char: "度", romaji: "do / tabi", meaning: "degree / time" },
  { char: "毎", romaji: "mai / goto", meaning: "every / each" },
  { char: "週", romaji: "shuu", meaning: "week" },
  { char: "間", romaji: "kan / aida", meaning: "interval / between" },
  { char: "午", romaji: "go", meaning: "noon" },
  { char: "食", romaji: "shoku / taberu", meaning: "eat / food" },
  { char: "飲", romaji: "in / nomu", meaning: "drink" },
  { char: "行", romaji: "kou / iku", meaning: "go" },
  { char: "来", romaji: "rai / kuru", meaning: "come" },
  { char: "帰", romaji: "ki / kaeru", meaning: "return" },
  { char: "見", romaji: "ken / miru", meaning: "see / watch" },
  { char: "聞", romaji: "bun / kiku", meaning: "hear / ask" },
  { char: "話", romaji: "wa / hanasu", meaning: "speak / talk" },
  { char: "読", romaji: "doku / yomu", meaning: "read" },
  { char: "書", romaji: "sho / kaku", meaning: "write" },
  { char: "言", romaji: "gen / iu", meaning: "say / word" },
  { char: "思", romaji: "shi / omou", meaning: "think" },
  { char: "知", romaji: "chi / shiru", meaning: "know" },
  { char: "長", romaji: "chou / nagai", meaning: "long / leader" },
  { char: "白", romaji: "haku / shiroi", meaning: "white" },
  { char: "天", romaji: "ten / ame", meaning: "heaven / sky" },
  { char: "気", romaji: "ki / ke", meaning: "spirit / energy" },
  { char: "多", romaji: "ta / ooi", meaning: "many / much" },
  { char: "少", romaji: "shou / sukunai", meaning: "few / little" },
  { char: "安", romaji: "an / yasui", meaning: "peace / cheap" },
  { char: "新", romaji: "shin / atarashii", meaning: "new" },
  { char: "古", romaji: "ko / furui", meaning: "old" },
  { char: "高", romaji: "kou / takai", meaning: "high / expensive" },
  { char: "買", romaji: "bai / kau", meaning: "buy" },
  { char: "物", romaji: "butsu / mono", meaning: "thing / object" },
  { char: "道", romaji: "dou / michi", meaning: "road / way" },
  { char: "車", romaji: "sha / kuruma", meaning: "car / vehicle" },
  { char: "花", romaji: "ka / hana", meaning: "flower" },
  { char: "林", romaji: "rin / hayashi", meaning: "grove / forest" },
  { char: "森", romaji: "shin / mori", meaning: "forest" },
  { char: "足", romaji: "soku / ashi", meaning: "foot / leg" },
  { char: "手", romaji: "shu / te", meaning: "hand" },
  { char: "口", romaji: "kou / kuchi", meaning: "mouth" },
  { char: "耳", romaji: "ji / mimi", meaning: "ear" },
  { char: "目", romaji: "moku / me", meaning: "eye" },
  { char: "頭", romaji: "tou / atama", meaning: "head" },
  { char: "顔", romaji: "gan / kao", meaning: "face" },
  { char: "体", romaji: "tai / karada", meaning: "body" },
  { char: "毛", romaji: "mou / ke", meaning: "hair / fur" },
  { char: "鼻", romaji: "bi / hana", meaning: "nose" },
  { char: "歯", romaji: "shi / ha", meaning: "tooth" },
  { char: "羽", romaji: "u / hane", meaning: "feather / wing" },
  { char: "肉", romaji: "niku", meaning: "meat / flesh" },
  { char: "血", romaji: "ketsu / chi", meaning: "blood" },
  { char: "骨", romaji: "kotsu / hone", meaning: "bone" },
  { char: "皮", romaji: "hi / kawa", meaning: "skin / leather" },
  { char: "声", romaji: "sei / koe", meaning: "voice" },
  { char: "涙", romaji: "rui / namida", meaning: "tear" },
  { char: "石", romaji: "seki / ishi", meaning: "stone" },
  { char: "空", romaji: "kuu / sora", meaning: "sky / empty" },
  { char: "雨", romaji: "u / ame", meaning: "rain" },
  { char: "雪", romaji: "setsu / yuki", meaning: "snow" },
  { char: "雲", romaji: "un / kumo", meaning: "cloud" },
  { char: "山", romaji: "san / yama", meaning: "mountain" },
  { char: "川", romaji: "sen / kawa", meaning: "river" },
  { char: "海", romaji: "kai / umi", meaning: "sea" },
  { char: "島", romaji: "tou / shima", meaning: "island" },
  { char: "池", romaji: "chi / ike", meaning: "pond" },
  { char: "湖", romaji: "ko / mizuumi", meaning: "lake" },
  { char: "谷", romaji: "tani / ya", meaning: "valley" },
  { char: "野", romaji: "ya / no", meaning: "field / plain" },
  { char: "田", romaji: "den / ta", meaning: "rice field" },
  { char: "氷", romaji: "hyou / koori", meaning: "ice" },
  { char: "波", romaji: "ha / nami", meaning: "wave" },
  { char: "風", romaji: "fuu / kaze", meaning: "wind / style" },
  { char: "岩", romaji: "gan / iwa", meaning: "rock / boulder" },
  { char: "砂", romaji: "sa / suna", meaning: "sand" },
  { char: "泥", romaji: "dei / doro", meaning: "mud" },
  { char: "泉", romaji: "sen / izumi", meaning: "spring / fountain" },
  { char: "滝", romaji: "taki", meaning: "waterfall" },
  { char: "河", romaji: "ka / kawa", meaning: "river / stream" },
  { char: "湾", romaji: "wan", meaning: "bay / gulf" },
  { char: "浜", romaji: "hin / hama", meaning: "beach / shore" },
  { char: "岸", romaji: "gan / kishi", meaning: "shore / bank" },
  { char: "潮", romaji: "chou / ushio", meaning: "tide" },
  { char: "雷", romaji: "rai / kaminari", meaning: "thunder" },
  { char: "霜", romaji: "sou / shimo", meaning: "frost" },
  { char: "霧", romaji: "mu / kiri", meaning: "fog / mist" },
  { char: "煙", romaji: "en / kemuri", meaning: "smoke" },
  { char: "根", romaji: "kon / ne", meaning: "root" },
  { char: "葉", romaji: "you / ha", meaning: "leaf" },
  { char: "果", romaji: "ka / hatasu", meaning: "fruit / accomplish" },
  { char: "実", romaji: "jitsu / mi", meaning: "truth / fruit" },
  { char: "町", romaji: "chou / machi", meaning: "town" },
  { char: "村", romaji: "son / mura", meaning: "village" },
  { char: "市", romaji: "shi / ichi", meaning: "city / market" },
  { char: "都", romaji: "to / miyako", meaning: "metropolis / capital" },
  { char: "府", romaji: "fu", meaning: "urban prefecture" },
  { char: "県", romaji: "ken", meaning: "prefecture" },
  { char: "店", romaji: "ten / mise", meaning: "shop / store" },
  { char: "社", romaji: "sha / yashiro", meaning: "company / shrine" },
  { char: "院", romaji: "in", meaning: "institution" },
  { char: "館", romaji: "kan / yakata", meaning: "hall / building" },
  { char: "屋", romaji: "oku / ya", meaning: "roof / shop" },
  { char: "駅", romaji: "eki", meaning: "station" },
  { char: "港", romaji: "kou / minato", meaning: "harbor / port" },
  { char: "橋", romaji: "kyou / hashi", meaning: "bridge" },
  { char: "門", romaji: "mon / kado", meaning: "gate" },
  { char: "窓", romaji: "sou / mado", meaning: "window" },
  { char: "壁", romaji: "heki / kabe", meaning: "wall" },
  { char: "床", romaji: "shou / yuka", meaning: "floor / bed" },
  { char: "庭", romaji: "tei / niwa", meaning: "garden / yard" },
  { char: "戸", romaji: "ko / to", meaning: "door" },
  { char: "園", romaji: "en / sono", meaning: "garden / park" },
  { char: "宮", romaji: "kyuu / miya", meaning: "palace / shrine" },
  { char: "殿", romaji: "den / tono", meaning: "palace / lord" },
  { char: "城", romaji: "jou / shiro", meaning: "castle" },
  { char: "寺", romaji: "ji / tera", meaning: "temple" },
  { char: "路", romaji: "ro / ji", meaning: "road / path" },
  { char: "堂", romaji: "dou", meaning: "hall" },
  { char: "台", romaji: "dai", meaning: "stand / platform" },
  { char: "原", romaji: "gen / hara", meaning: "field / origin" },
  { char: "茶", romaji: "cha / sa", meaning: "tea" },
  { char: "卵", romaji: "ran / tamago", meaning: "egg" },
  { char: "飯", romaji: "han / meshi", meaning: "meal / rice" },
  { char: "味", romaji: "mi / aji", meaning: "taste / flavor" },
  { char: "菜", romaji: "sai / na", meaning: "vegetable / greens" },
  { char: "酒", romaji: "shu / sake", meaning: "alcohol / sake" },
  { char: "乳", romaji: "nyuu / chichi", meaning: "milk / breast" },
  { char: "豆", romaji: "tou / mame", meaning: "bean / pea" },
  { char: "麦", romaji: "baku / mugi", meaning: "wheat / barley" },
  { char: "米", romaji: "bei / kome", meaning: "rice" },
  { char: "粉", romaji: "fun / kona", meaning: "powder / flour" },
  { char: "油", romaji: "yu / abura", meaning: "oil" },
  { char: "塩", romaji: "en / shio", meaning: "salt" },
  { char: "汁", romaji: "juu / shiru", meaning: "juice / soup" },
  { char: "服", romaji: "fuku", meaning: "clothes" },
  { char: "靴", romaji: "ka / kutsu", meaning: "shoes" },
  { char: "傘", romaji: "san / kasa", meaning: "umbrella" },
  { char: "紙", romaji: "shi / kami", meaning: "paper" },
  { char: "辞", romaji: "ji", meaning: "word / resign" },
  { char: "典", romaji: "ten", meaning: "code / dictionary" },
  { char: "絵", romaji: "e / kai", meaning: "picture / painting" },
  { char: "画", romaji: "ga / kaku", meaning: "picture / draw" },
  { char: "机", romaji: "ki / tsukue", meaning: "desk" },
  { char: "袋", romaji: "tai / fukuro", meaning: "bag / sack" },
  { char: "箱", romaji: "sou / hako", meaning: "box" },
  { char: "缶", romaji: "kan", meaning: "can / tin" },
  { char: "瓶", romaji: "bin", meaning: "bottle / jar" },
  { char: "針", romaji: "shin / hari", meaning: "needle" },
  { char: "糸", romaji: "shi / ito", meaning: "thread" },
  { char: "布", romaji: "fu / nuno", meaning: "cloth" },
  { char: "切", romaji: "setsu / kiru", meaning: "cut" },
  { char: "運", romaji: "un / hakobu", meaning: "carry / transport" },
  { char: "動", romaji: "dou / ugoku", meaning: "move" },
  { char: "仕", romaji: "shi / tsukamatsuru", meaning: "serve / do" },
  { char: "事", romaji: "ji / koto", meaning: "thing / matter" },
  { char: "勉", romaji: "ben / tsutomeru", meaning: "exertion / effort" },
  { char: "強", romaji: "kyou / tsuyoi", meaning: "strong" },
  { char: "料", romaji: "ryou", meaning: "material / fee" },
  { char: "理", romaji: "ri / kotowari", meaning: "reason / logic" },
  { char: "旅", romaji: "ryo / tabi", meaning: "travel / trip" },
  { char: "散", romaji: "san / chirasu", meaning: "scatter" },
  { char: "歩", romaji: "ho / aruku", meaning: "walk / step" },
  { char: "作", romaji: "saku / tsukuru", meaning: "make / create" },
  { char: "使", romaji: "shi / tsukau", meaning: "use" },
  { char: "借", romaji: "shaku / kariru", meaning: "borrow" },
  { char: "待", romaji: "tai / matsu", meaning: "wait" },
  { char: "打", romaji: "da / utsu", meaning: "hit" },
  { char: "投", romaji: "tou / nageru", meaning: "throw" },
  { char: "持", romaji: "ji / motsu", meaning: "hold / have" },
  { char: "指", romaji: "shi / yubi", meaning: "finger / point" },
  { char: "拾", romaji: "shuu / hirou", meaning: "pick up" },
  { char: "放", romaji: "hou / hanatsu", meaning: "release / set free" },
  { char: "引", romaji: "in / hiku", meaning: "pull" },
  { char: "送", romaji: "sou / okuru", meaning: "send" },
  { char: "通", romaji: "tsuu / kayou", meaning: "pass / commute" },
  { char: "達", romaji: "tatsu", meaning: "reach / accomplish" },
  { char: "進", romaji: "shin / susumu", meaning: "advance" },
  { char: "止", romaji: "shi / tomaru", meaning: "stop" },
  { char: "改", romaji: "kai / aratameru", meaning: "reform / change" },
  { char: "変", romaji: "hen / kawaru", meaning: "change / strange" },
  { char: "化", romaji: "ka / baka", meaning: "change / transform" },
  { char: "始", romaji: "shi / hajimeru", meaning: "begin" },
  { char: "終", romaji: "shuu / owaru", meaning: "end / finish" },
  { char: "開", romaji: "kai / hiraku", meaning: "open" },
  { char: "閉", romaji: "hei / shimeru", meaning: "close" },
  { char: "回", romaji: "kai / mawaru", meaning: "turn / around" },
  { char: "転", romaji: "ten / korobu", meaning: "revolve / change" },
  { char: "続", romaji: "zoku / tsuzuku", meaning: "continue" },
  { char: "接", romaji: "setsu / tsugu", meaning: "contact / connect" },
  { char: "渡", romaji: "to / wataru", meaning: "cross / ferry" },
  { char: "越", romaji: "etsu / kosu", meaning: "exceed / go beyond" },
  { char: "超", romaji: "chou / koeru", meaning: "exceed / super" },
  { char: "集", romaji: "shuu / atsumaru", meaning: "gather / collect" },
  { char: "乗", romaji: "jou / noru", meaning: "ride / board" },
  { char: "降", romaji: "kou / oriru", meaning: "descend / get off" },
  { char: "健", romaji: "ken / sukoyaka", meaning: "health" },
  { char: "康", romaji: "kou", meaning: "health / ease" },
  { char: "医", romaji: "i", meaning: "doctor / medicine" },
  { char: "病", romaji: "byou / yamai", meaning: "sickness" },
  { char: "薬", romaji: "yaku / kusuri", meaning: "medicine" },
  { char: "心", romaji: "shin / kokoro", meaning: "heart" },
  { char: "悲", romaji: "hi / kanashii", meaning: "sad / grief" },
  { char: "怒", romaji: "do / ikaru", meaning: "anger" },
  { char: "恋", romaji: "ren / koi", meaning: "love / romance" },
  { char: "感", romaji: "kan", meaning: "feeling" },
  { char: "情", romaji: "jou / nasake", meaning: "emotion / feeling" },
  { char: "想", romaji: "sou / omou", meaning: "think / imagine" },
  { char: "意", romaji: "i", meaning: "mind / intention" },
  { char: "考", romaji: "kou / kangaeru", meaning: "think / consider" },
  { char: "決", romaji: "ketsu / kimeru", meaning: "decide" },
  { char: "定", romaji: "tei / sadameru", meaning: "determine / fix" },
  { char: "必", romaji: "hitsu / kanarazu", meaning: "inevitable / certain" },
  { char: "要", romaji: "you / iru", meaning: "need / essential" },
  { char: "許", romaji: "kyo / yurusu", meaning: "permit / allow" },
  { char: "認", romaji: "nin / mitomeru", meaning: "recognize" },
  { char: "可", romaji: "ka", meaning: "possible / approve" },
  { char: "否", romaji: "hi / ina", meaning: "no / negative" },
  { char: "好", romaji: "kou / suku", meaning: "like / fond" },
  { char: "嫌", romaji: "ken / kiru", meaning: "dislike / hate" },
  { char: "望", romaji: "bou / nozomu", meaning: "hope / desire" },
  { char: "悪", romaji: "aku / warui", meaning: "bad / evil" },
  { char: "正", romaji: "sei / tadashii", meaning: "correct / right" },
  { char: "負", romaji: "fu / makeru", meaning: "negative / lose" },
  { char: "明", romaji: "mei / akarui", meaning: "bright / clear" },
  { char: "暗", romaji: "an / kurai", meaning: "dark" },
  { char: "広", romaji: "kou / hiroi", meaning: "wide / broad" },
  { char: "狭", romaji: "kyou / semai", meaning: "narrow" },
  { char: "遠", romaji: "en / tooi", meaning: "far / distant" },
  { char: "近", romaji: "kin / chikai", meaning: "near / close" },
  { char: "早", romaji: "sou / hayai", meaning: "early / fast" },
  { char: "遅", romaji: "chi / osoi", meaning: "slow / late" },
  { char: "速", romaji: "soku / hayai", meaning: "fast / speed" },
  { char: "弱", romaji: "jaku / yowai", meaning: "weak" },
  { char: "有", romaji: "yuu / aru", meaning: "have / exist" },
  { char: "無", romaji: "mu / nai", meaning: "nothing / without" },
  { char: "同", romaji: "dou / onaji", meaning: "same" },
  { char: "違", romaji: "i / chigau", meaning: "different" },
  { char: "昔", romaji: "seki / mukashi", meaning: "old times / long ago" },
  { char: "春", romaji: "shun / haru", meaning: "spring" },
  { char: "夏", romaji: "ka / natsu", meaning: "summer" },
  { char: "秋", romaji: "shuu / aki", meaning: "autumn" },
  { char: "冬", romaji: "tou / fuyu", meaning: "winter" },
  { char: "朝", romaji: "chou / asa", meaning: "morning" },
  { char: "昼", romaji: "chuu / hiru", meaning: "daytime / noon" },
  { char: "晩", romaji: "ban", meaning: "evening" },
  { char: "夜", romaji: "ya / yoru", meaning: "night" },
  { char: "暑", romaji: "sho / atsui", meaning: "hot (weather)" },
  { char: "寒", romaji: "kan / samui", meaning: "cold" },
  { char: "暖", romaji: "dan / atatakai", meaning: "warm" },
  { char: "涼", romaji: "ryou / suzushii", meaning: "cool / refreshing" },
  { char: "静", romaji: "sei / shizuka", meaning: "quiet / calm" },
  { char: "忙", romaji: "bou / isogashii", meaning: "busy" },
  { char: "危", romaji: "ki / abunai", meaning: "dangerous" },
  { char: "難", romaji: "nan / muzukashii", meaning: "difficult" },
  { char: "易", romaji: "i / yasashii", meaning: "easy / simple" },
  { char: "世", romaji: "sei / yo", meaning: "world / generation" },
  { char: "主", romaji: "shu / nushi", meaning: "main / owner" },
  { char: "京", romaji: "kyou / miyako", meaning: "capital" },
  { char: "代", romaji: "dai / kawaru", meaning: "generation / substitute" },
  { char: "以", romaji: "i", meaning: "by means of / since" },
  { char: "住", romaji: "juu / sumu", meaning: "dwell / live" },
  { char: "係", romaji: "kei / kakari", meaning: "person in charge" },
  { char: "値", romaji: "chi / ne", meaning: "value / price" },
  { char: "億", romaji: "oku", meaning: "hundred million" },
  { char: "光", romaji: "kou / hikari", meaning: "light" },
  { char: "兄", romaji: "kei / ani", meaning: "older brother" },
  { char: "弟", romaji: "dai / otouto", meaning: "younger brother" },
  { char: "姉", romaji: "shi / ane", meaning: "older sister" },
  { char: "妹", romaji: "mai / imouto", meaning: "younger sister" },
  { char: "親", romaji: "shin / oya", meaning: "parent" },
  { char: "族", romaji: "zoku", meaning: "family / clan" },
  { char: "民", romaji: "min / tami", meaning: "people / nation" },
  { char: "氏", romaji: "shi / uji", meaning: "surname / clan" },
  { char: "官", romaji: "kan", meaning: "government official" },
  { char: "軍", romaji: "gun", meaning: "army / military" },
  { char: "隊", romaji: "tai", meaning: "group / squad" },
  { char: "者", romaji: "sha / mono", meaning: "person" },
  { char: "様", romaji: "you / sama", meaning: "way / Mr. / Ms." },
  { char: "君", romaji: "kun / kimi", meaning: "you / lord" },
  { char: "神", romaji: "shin / kami", meaning: "god / spirit" },
  { char: "全", romaji: "zen / mattabu", meaning: "whole / entire" },
  { char: "部", romaji: "bu", meaning: "part / section" },
  { char: "片", romaji: "hen / kata", meaning: "piece / fragment" },
  { char: "対", romaji: "tai", meaning: "opposite / against" },
  { char: "比", romaji: "hi / kuraberu", meaning: "compare / ratio" },
  { char: "例", romaji: "rei / tatoeru", meaning: "example" },
  { char: "表", romaji: "hyou / arawasu", meaning: "express / surface" },
  { char: "現", romaji: "gen / arawareru", meaning: "appear / current" },
  { char: "際", romaji: "sai / kiwa", meaning: "occasion / border" },
  { char: "関", romaji: "kan / seki", meaning: "relate / barrier" },
  { char: "応", romaji: "ou", meaning: "respond / apply" },
  { char: "活", romaji: "katsu", meaning: "lively / active" },
  { char: "発", romaji: "hatsu", meaning: "departure / emit" },
  { char: "展", romaji: "ten", meaning: "expand" },
  { char: "備", romaji: "bi / sonaeru", meaning: "equip / provide" },
  { char: "査", romaji: "sa", meaning: "investigate" },
  { char: "検", romaji: "ken", meaning: "examine / inspect" },
  { char: "討", romaji: "tou", meaning: "discuss / debate" },
  { char: "論", romaji: "ron", meaning: "argument / theory" },
  { char: "議", romaji: "gi", meaning: "deliberation / council" },
  { char: "共", romaji: "kyou / tomo", meaning: "together / shared" },
  { char: "点", romaji: "ten", meaning: "point / dot" },
  { char: "線", romaji: "sen", meaning: "line" },
  { char: "面", romaji: "men / omo", meaning: "surface / face" },
  { char: "積", romaji: "seki / tsumu", meaning: "accumulate / product" },
  { char: "製", romaji: "sei", meaning: "manufacture" },
  { char: "品", romaji: "hin / shina", meaning: "product / goods" },
  { char: "量", romaji: "ryou / hakaru", meaning: "quantity" },
  { char: "数", romaji: "suu / kazu", meaning: "number" },
  { char: "産", romaji: "san / umu", meaning: "produce / give birth" },
  { char: "業", romaji: "gyou / waza", meaning: "business / industry" },
  { char: "賞", romaji: "shou", meaning: "prize / reward" },
  { char: "担", romaji: "tan / ninau", meaning: "bear / carry" },
  { char: "増", romaji: "zou / masu", meaning: "increase" },
  { char: "減", romaji: "gen / heru", meaning: "decrease" },
  { char: "得", romaji: "toku / eru", meaning: "gain / profit" },
  { char: "失", romaji: "shitsu / ushinau", meaning: "lose" },
  { char: "在", romaji: "zai / aru", meaning: "exist / be located" },
  { char: "向", romaji: "kou / muku", meaning: "face / turn toward" },
  { char: "治", romaji: "chi / osameru", meaning: "govern / peace" },
  { char: "経", romaji: "kei / heru", meaning: "manage / pass" },
  { char: "済", romaji: "sai / sumu", meaning: "settle / finish" },
  { char: "費", romaji: "hi / tsuiyasu", meaning: "expense / cost" },
  { char: "貯", romaji: "cho / takuwaeru", meaning: "save / store" },
  { char: "貸", romaji: "tai / kasu", meaning: "lend" },
  { char: "払", romaji: "futsu / harau", meaning: "pay" },
  { char: "協", romaji: "kyou", meaning: "cooperate" },
  { char: "申", romaji: "shin / mousu", meaning: "say / humbly" },
  { char: "伝", romaji: "den / tsutaeru", meaning: "transmit / convey" },
  { char: "状", romaji: "jou", meaning: "condition / letter" },
  { char: "態", romaji: "tai", meaning: "attitude / condition" },
  { char: "相", romaji: "sou / ai", meaning: "mutual / phase" },
  { char: "観", romaji: "kan", meaning: "view / observe" },
  { char: "承", romaji: "shou / uketamawaru", meaning: "consent / agree" },
  { char: "法", romaji: "hou", meaning: "law / method" },
  { char: "則", romaji: "soku", meaning: "rule" },
  { char: "判", romaji: "han", meaning: "judge" },
  { char: "断", romaji: "dan / tatsu", meaning: "decide / cut off" },
  { char: "基", romaji: "ki / moto", meaning: "base / foundation" },
  { char: "礎", romaji: "so", meaning: "cornerstone" },
  { char: "標", romaji: "hyou", meaning: "sign / mark" },
  { char: "準", romaji: "jun", meaning: "standard" },
  { char: "計", romaji: "kei / hakaru", meaning: "measure / plan" },
  { char: "平", romaji: "hei / hira", meaning: "flat / peace" },
  { char: "均", romaji: "kin", meaning: "equal / average" },
  { char: "最", romaji: "sai / mottomo", meaning: "most / extreme" },
  { char: "因", romaji: "in / yoru", meaning: "cause / reason" },
  { char: "結", romaji: "ketsu / musubu", meaning: "tie / bind / conclude" },
  { char: "構", romaji: "kou / kamaeru", meaning: "structure / build" },
  { char: "精", romaji: "sei", meaning: "spirit / refined" },
  { char: "的", romaji: "teki / mato", meaning: "target / -like" },
  { char: "確", romaji: "kaku / tashika", meaning: "certain / sure" },
  { char: "説", romaji: "setsu / toku", meaning: "theory / explain" },
  { char: "解", romaji: "kai / toku", meaning: "solve / unravel" },
  { char: "牛", romaji: "gyuu / ushi", meaning: "cow" },
  { char: "鳥", romaji: "chou / tori", meaning: "bird" },
  { char: "犬", romaji: "ken / inu", meaning: "dog" },
  { char: "猫", romaji: "byou / neko", meaning: "cat" },
  { char: "魚", romaji: "gyo / sakana", meaning: "fish" },
  { char: "船", romaji: "sen / fune", meaning: "ship / boat" },
  { char: "馬", romaji: "ba / uma", meaning: "horse" },
  { char: "電", romaji: "den", meaning: "electricity" },
  { char: "教", romaji: "kyou / oshieru", meaning: "teach" },
  { char: "室", romaji: "shitsu / muro", meaning: "room" },
  { char: "試", romaji: "shi / kokoromiru", meaning: "test / try" },
  { char: "験", romaji: "ken", meaning: "test / verify" },
  { char: "質", romaji: "shitsu / tachi", meaning: "quality / substance" },
  { char: "問", romaji: "mon / tou", meaning: "question / problem" },
  { char: "答", romaji: "tou / kotaeru", meaning: "answer" },
  { char: "郵", romaji: "yuu", meaning: "mail" },
  { char: "便", romaji: "ben / bin", meaning: "convenience / mail" },
  { char: "局", romaji: "kyoku", meaning: "bureau / office" },
  { char: "銀", romaji: "gin", meaning: "silver" },
  { char: "図", romaji: "zu / hakarigoto", meaning: "diagram / map" },
  { char: "公", romaji: "kou / ooyake", meaning: "public / fair" },
  { char: "植", romaji: "shoku / ueru", meaning: "plant" },
  { char: "特", romaji: "toku", meaning: "special" },
  { char: "別", romaji: "betsu / wakareru", meaning: "separate / different" },
  { char: "勝", romaji: "shou / katsu", meaning: "win / victory" },
  { char: "輸", romaji: "yu", meaning: "transport" },
  { char: "導", romaji: "dou / michibiku", meaning: "guide / lead" },
  { char: "配", romaji: "hai / kubaru", meaning: "distribute" },
  { char: "重", romaji: "juu / omoi", meaning: "heavy / important" },
  { char: "軽", romaji: "kei / karui", meaning: "light (weight)" },
  { char: "限", romaji: "gen / kagiru", meaning: "limit" },
  { char: "階", romaji: "kai", meaning: "floor / story" },
  { char: "題", romaji: "dai", meaning: "title / topic" },
  { char: "養", romaji: "you / yashinau", meaning: "nurture / raise" },
  { char: "究", romaji: "kyuu / kiwameru", meaning: "research" },
  { char: "守", romaji: "shu / mamoru", meaning: "protect / obey" },
  { char: "家", romaji: "ka / ie", meaning: "house / home" },
  { char: "席", romaji: "seki", meaning: "seat" },
  { char: "庫", romaji: "ko / kura", meaning: "warehouse / store" },
  { char: "形", romaji: "kei / katachi", meaning: "shape / form" },
  { char: "役", romaji: "yaku / eki", meaning: "role / duty" },
  { char: "所", romaji: "sho / tokoro", meaning: "place" },
  { char: "次", romaji: "ji / tsugi", meaning: "next" },
  { char: "段", romaji: "dan", meaning: "step / stage" },
  { char: "注", romaji: "chuu / sosogu", meaning: "pour / pay attention" },
  { char: "由", romaji: "yuu / yoshi", meaning: "reason / cause" },
  { char: "利", romaji: "ri / kiku", meaning: "profit / benefit" },
  { char: "害", romaji: "gai", meaning: "harm / damage" },
  { char: "険", romaji: "ken / kewashii", meaning: "steep / dangerous" },
  { char: "楽", romaji: "raku / tanoshii", meaning: "comfort / enjoyable" },
  { char: "候", romaji: "kou / sorou", meaning: "weather / sign" },
  { char: "熱", romaji: "netsu / atsui", meaning: "heat / fever" },
  { char: "冷", romaji: "rei / tsumetai", meaning: "cold / cool" },
  { char: "温", romaji: "on / atatakai", meaning: "warm / temperature" },
  { char: "太", romaji: "tai / futoi", meaning: "thick / fat" },
  { char: "細", romaji: "sai / hosoi", meaning: "thin / slender" },
  { char: "横", romaji: "ou / yoko", meaning: "side / horizontal" },
  { char: "縦", romaji: "juu / tate", meaning: "vertical / length" },
  { char: "留", romaji: "ryuu / tomeru", meaning: "stop / stay" },
  { char: "笑", romaji: "shou / warau", meaning: "laugh / smile" },
  { char: "泣", romaji: "kyuu / naku", meaning: "cry / weep" },
  { char: "号", romaji: "gou", meaning: "number / name" },
  { char: "筆", romaji: "hitsu / fude", meaning: "brush / writing" },
  { char: "墨", romaji: "boku / sumi", meaning: "ink / black" },
  { char: "皿", romaji: "bei / sara", meaning: "plate / dish" },
  { char: "札", romaji: "satsu / fuda", meaning: "bill / tag" },
  { char: "券", romaji: "ken", meaning: "ticket / certificate" },
  { char: "念", romaji: "nen", meaning: "thought / concern" },
  { char: "筆", romaji: "hitsu / fude", meaning: "brush / writing" },
  { char: "紙", romaji: "shi / kami", meaning: "paper" },
  { char: "米", romaji: "bei / kome", meaning: "rice / America" },
  { char: "茶", romaji: "cha", meaning: "tea" },
  { char: "京", romaji: "kyou / kei", meaning: "capital / Tokyo" },
  { char: "府", romaji: "fu", meaning: "urban prefecture" },
  { char: "県", romaji: "ken", meaning: "prefecture" },
  { char: "村", romaji: "son / mura", meaning: "village" },
  { char: "町", romaji: "chou / machi", meaning: "town / street" },
  { char: "港", romaji: "kou / minato", meaning: "harbor / port" },
  { char: "橋", romaji: "kyou / hashi", meaning: "bridge" },
  { char: "駅", romaji: "eki", meaning: "station" },
  { char: "船", romaji: "sen / fune", meaning: "ship / boat" },
  { char: "服", romaji: "fuku", meaning: "clothes" },
  { char: "顔", romaji: "gan / kao", meaning: "face" },
  { char: "声", romaji: "sei / koe", meaning: "voice" }
];
const hiraganaGroups = [
  { key: "a-row", label: "Vowels (a)" },
  { key: "ka-row", label: "K" },
  { key: "sa-row", label: "S" },
  { key: "ta-row", label: "T" },
  { key: "na-row", label: "N" },
  { key: "ha-row", label: "H" },
  { key: "ma-row", label: "M" },
  { key: "ya-row", label: "Y" },
  { key: "ra-row", label: "R" },
  { key: "wa-row", label: "W" },
  { key: "n-row", label: "N (ん)" },
  { key: "ga-row", label: "G (dakuten)" },
  { key: "za-row", label: "Z (dakuten)" },
  { key: "da-row", label: "D (dakuten)" },
  { key: "ba-row", label: "B (dakuten)" },
  { key: "pa-row", label: "P (handakuten)" }
];

const katakanaGroups = [
  { key: "a-row", label: "Vowels (a)" },
  { key: "ka-row", label: "K" },
  { key: "sa-row", label: "S" },
  { key: "ta-row", label: "T" },
  { key: "na-row", label: "N" },
  { key: "ha-row", label: "H" },
  { key: "ma-row", label: "M" },
  { key: "ya-row", label: "Y" },
  { key: "ra-row", label: "R" },
  { key: "wa-row", label: "W" },
  { key: "n-row", label: "N (ン)" },
  { key: "ga-row", label: "G (dakuten)" },
  { key: "za-row", label: "Z (dakuten)" },
  { key: "da-row", label: "D (dakuten)" },
  { key: "ba-row", label: "B (dakuten)" },
  { key: "pa-row", label: "P (handakuten)" }
];

const vocabData = [
  { japanese: "食べる", reading: "たべる", english: "to eat" },
  { japanese: "飲む", reading: "のむ", english: "to drink" },
  { japanese: "行く", reading: "いく", english: "to go" },
  { japanese: "来る", reading: "くる", english: "to come" },
  { japanese: "見る", reading: "みる", english: "to see / to watch" },
  { japanese: "聞く", reading: "きく", english: "to hear / to listen" },
  { japanese: "話す", reading: "はなす", english: "to speak / to talk" },
  { japanese: "読む", reading: "よむ", english: "to read" },
  { japanese: "書く", reading: "かく", english: "to write" },
  { japanese: "買う", reading: "かう", english: "to buy" },
  { japanese: "作る", reading: "つくる", english: "to make" },
  { japanese: "待つ", reading: "まつ", english: "to wait" },
  { japanese: "持つ", reading: "もつ", english: "to hold / to carry" },
  { japanese: "知る", reading: "しる", english: "to know" },
  { japanese: "思う", reading: "おもう", english: "to think" },
  { japanese: "言う", reading: "いう", english: "to say" },
  { japanese: "出す", reading: "だす", english: "to take out / to put out" },
  { japanese: "入れる", reading: "いれる", english: "to put in" },
  { japanese: "開ける", reading: "あける", english: "to open" },
  { japanese: "閉める", reading: "しめる", english: "to close" },
  { japanese: "始める", reading: "はじめる", english: "to start / to begin" },
  { japanese: "終わる", reading: "おわる", english: "to end / to finish" },
  { japanese: "勉強する", reading: "べんきょうする", english: "to study" },
  { japanese: "働く", reading: "はたらく", english: "to work" },
  { japanese: "帰る", reading: "かえる", english: "to return home" },
  { japanese: "歩く", reading: "あるく", english: "to walk" },
  { japanese: "走る", reading: "はしる", english: "to run" },
  { japanese: "泳ぐ", reading: "およぐ", english: "to swim" },
  { japanese: "寝る", reading: "ねる", english: "to sleep" },
  { japanese: "起きる", reading: "おきる", english: "to get up" },
  { japanese: "教える", reading: "おしえる", english: "to teach" },
  { japanese: "借りる", reading: "かりる", english: "to borrow" },
  { japanese: "貸す", reading: "かす", english: "to lend" },
  { japanese: "使う", reading: "つかう", english: "to use" },
  { japanese: "会う", reading: "あう", english: "to meet" },
  { japanese: "考える", reading: "かんがえる", english: "to think / to consider" },
  { japanese: "決める", reading: "きめる", english: "to decide" },
  { japanese: "忘れる", reading: "わすれる", english: "to forget" },
  { japanese: "なくす", reading: "なくす", english: "to lose" },
  { japanese: "住む", reading: "すむ", english: "to live / to reside" },
  { japanese: "大きい", reading: "おおきい", english: "big" },
  { japanese: "小さい", reading: "ちいさい", english: "small" },
  { japanese: "新しい", reading: "あたらしい", english: "new" },
  { japanese: "古い", reading: "ふるい", english: "old" },
  { japanese: "安い", reading: "やすい", english: "cheap" },
  { japanese: "高い", reading: "たかい", english: "expensive / tall" },
  { japanese: "美味しい", reading: "おいしい", english: "delicious" },
  { japanese: "楽しい", reading: "たのしい", english: "fun" },
  { japanese: "嬉しい", reading: "うれしい", english: "happy" },
  { japanese: "悲しい", reading: "かなしい", english: "sad" },
  { japanese: "早い", reading: "はやい", english: "fast / early" },
  { japanese: "遅い", reading: "おそい", english: "slow / late" },
  { japanese: "暑い", reading: "あつい", english: "hot (weather)" },
  { japanese: "寒い", reading: "さむい", english: "cold (weather)" },
  { japanese: "温かい", reading: "あたたかい", english: "warm" },
  { japanese: "涼しい", reading: "すずしい", english: "cool / refreshing" },
  { japanese: "面白い", reading: "おもしろい", english: "interesting / funny" },
  { japanese: "難しい", reading: "むずかしい", english: "difficult" },
  { japanese: "易しい", reading: "やさしい", english: "easy" },
  { japanese: "若い", reading: "わかい", english: "young" },
  { japanese: "元気", reading: "げんき", english: "energetic / healthy" },
  { japanese: "静か", reading: "しずか", english: "quiet" },
  { japanese: "賑やか", reading: "にぎやか", english: "lively / busy" },
  { japanese: "便利", reading: "べんり", english: "convenient" },
  { japanese: "好き", reading: "すき", english: "liked / favorite" },
  { japanese: "嫌い", reading: "きらい", english: "disliked" },
  { japanese: "有名", reading: "ゆうめい", english: "famous" },
  { japanese: "親切", reading: "しんせつ", english: "kind" },
  { japanese: "大変", reading: "たいへん", english: "tough / hard" },
  { japanese: "必要", reading: "ひつよう", english: "necessary" },
  { japanese: "簡単", reading: "かんたん", english: "simple / easy" },
  { japanese: "大丈夫", reading: "だいじょうぶ", english: "okay / fine" },
  { japanese: "同じ", reading: "おなじ", english: "same" },
  { japanese: "駄目", reading: "だめ", english: "no good / useless" },
  { japanese: "嫌", reading: "いや", english: "unpleasant / disliked" },
  { japanese: "今日", reading: "きょう", english: "today" },
  { japanese: "明日", reading: "あした", english: "tomorrow" },
  { japanese: "昨日", reading: "きのう", english: "yesterday" },
  { japanese: "毎日", reading: "まいにち", english: "every day" },
  { japanese: "毎週", reading: "まいしゅう", english: "every week" },
  { japanese: "毎年", reading: "まいとし", english: "every year" },
  { japanese: "今", reading: "いま", english: "now" },
  { japanese: "朝", reading: "あさ", english: "morning" },
  { japanese: "昼", reading: "ひる", english: "noon / afternoon" },
  { japanese: "夜", reading: "よる", english: "night" },
  { japanese: "夕方", reading: "ゆうがた", english: "evening" },
  { japanese: "午前", reading: "ごぜん", english: "AM / morning" },
  { japanese: "午後", reading: "ごご", english: "PM / afternoon" },
  { japanese: "週末", reading: "しゅうまつ", english: "weekend" },
  { japanese: "今週", reading: "こんしゅう", english: "this week" },
  { japanese: "来週", reading: "らいしゅう", english: "next week" },
  { japanese: "先週", reading: "せんしゅう", english: "last week" },
  { japanese: "今年", reading: "ことし", english: "this year" },
  { japanese: "来年", reading: "らいねん", english: "next year" },
  { japanese: "去年", reading: "きょねん", english: "last year" },
  { japanese: "私", reading: "わたし", english: "I / me" },
  { japanese: "先生", reading: "せんせい", english: "teacher" },
  { japanese: "友達", reading: "ともだち", english: "friend" },
  { japanese: "家族", reading: "かぞく", english: "family" },
  { japanese: "両親", reading: "りょうしん", english: "parents" },
  { japanese: "子供", reading: "こども", english: "child" },
  { japanese: "学生", reading: "がくせい", english: "student" },
  { japanese: "日本人", reading: "にほんじん", english: "Japanese person" },
  { japanese: "ご飯", reading: "ごはん", english: "rice / meal" },
  { japanese: "肉", reading: "にく", english: "meat" },
  { japanese: "魚", reading: "さかな", english: "fish" },
  { japanese: "野菜", reading: "やさい", english: "vegetable" },
  { japanese: "果物", reading: "くだもの", english: "fruit" },
  { japanese: "水", reading: "みず", english: "water" },
  { japanese: "お茶", reading: "おちゃ", english: "tea" },
  { japanese: "牛乳", reading: "ぎゅうにゅう", english: "milk" },
  { japanese: "卵", reading: "たまご", english: "egg" },
  { japanese: "料理", reading: "りょうり", english: "cooking / cuisine" },
  { japanese: "家", reading: "いえ", english: "house / home" },
  { japanese: "学校", reading: "がっこう", english: "school" },
  { japanese: "病院", reading: "びょういん", english: "hospital" },
  { japanese: "駅", reading: "えき", english: "station" },
  { japanese: "店", reading: "みせ", english: "shop / store" },
  { japanese: "会社", reading: "かいしゃ", english: "company" },
  { japanese: "公園", reading: "こうえん", english: "park" },
  { japanese: "図書館", reading: "としょかん", english: "library" },
  { japanese: "銀行", reading: "ぎんこう", english: "bank" },
  { japanese: "天気", reading: "てんき", english: "weather" },
  { japanese: "お金", reading: "おかね", english: "money" },
  { japanese: "仕事", reading: "しごと", english: "work / job" },
  { japanese: "電話", reading: "でんわ", english: "telephone" },
  { japanese: "名前", reading: "なまえ", english: "name" },
  { japanese: "国", reading: "くに", english: "country" },
  { japanese: "言葉", reading: "ことば", english: "word / language" },
  { japanese: "勉強", reading: "べんきょう", english: "study" },
  { japanese: "宿題", reading: "しゅくだい", english: "homework" },
  { japanese: "試験", reading: "しけん", english: "exam" },
  { japanese: "色", reading: "いろ", english: "color" },
  { japanese: "音", reading: "おと", english: "sound" },
  { japanese: "人", reading: "ひと", english: "person" },
  { japanese: "手", reading: "て", english: "hand" },
  { japanese: "目", reading: "め", english: "eye" },
  { japanese: "耳", reading: "みみ", english: "ear" },
  { japanese: "口", reading: "くち", english: "mouth" },
  { japanese: "頭", reading: "あたま", english: "head" },
  { japanese: "空", reading: "そら", english: "sky" },
  { japanese: "海", reading: "うみ", english: "sea / ocean" },
  { japanese: "山", reading: "やま", english: "mountain" },
  { japanese: "川", reading: "かわ", english: "river" },
  { japanese: "雨", reading: "あめ", english: "rain" },
  { japanese: "一つ", reading: "ひとつ", english: "one (thing)" },
  { japanese: "二つ", reading: "ふたつ", english: "two (things)" },
  { japanese: "三人", reading: "さんにん", english: "three people" },
  { japanese: "二階", reading: "にかい", english: "second floor" },
  { japanese: "一枚", reading: "いちまい", english: "one sheet / flat object" },
  { japanese: "とても", reading: "とても", english: "very" },
  { japanese: "少し", reading: "すこし", english: "a little" },
  { japanese: "もう", reading: "もう", english: "already / more" },
  { japanese: "まだ", reading: "まだ", english: "still / not yet" },
  { japanese: "いつも", reading: "いつも", english: "always" },
  { japanese: "よく", reading: "よく", english: "often / well" },
  { japanese: "たいへん", reading: "たいへん", english: "very / terrible" },
  { japanese: "ちょっと", reading: "ちょっと", english: "a little" },
  { japanese: "どうして", reading: "どうして", english: "why" },
  { japanese: "ぜひ", reading: "ぜひ", english: "by all means" },
  { japanese: "もちろん", reading: "もちろん", english: "of course" },
  { japanese: "絶対", reading: "ぜったい", english: "absolutely" },
  { japanese: "一緒に", reading: "いっしょに", english: "together" },
  { japanese: "すぐ", reading: "すぐ", english: "immediately" },
  { japanese: "初めて", reading: "はじめて", english: "for the first time" },
  { japanese: "誰", reading: "だれ", english: "who" },
  { japanese: "何", reading: "なに", english: "what" },
  { japanese: "どこ", reading: "どこ", english: "where" },
  { japanese: "いつ", reading: "いつ", english: "when" },
  { japanese: "どう", reading: "どう", english: "how" },
  { japanese: "こんにちは", reading: "こんにちは", english: "hello" },
  { japanese: "おはよう", reading: "おはよう", english: "good morning" },
  { japanese: "こんばんは", reading: "こんばんは", english: "good evening" },
  { japanese: "さようなら", reading: "さようなら", english: "goodbye" },
  { japanese: "ありがとう", reading: "ありがとう", english: "thank you" },
  { japanese: "すみません", reading: "すみません", english: "excuse me / sorry" },
  { japanese: "ごめんなさい", reading: "ごめんなさい", english: "I'm sorry" },
  { japanese: "お願いします", reading: "おねがいします", english: "please" },
  { japanese: "いただきます", reading: "いただきます", english: "before meal phrase" },
  { japanese: "ごちそうさま", reading: "ごちそうさま", english: "after meal phrase" },
  { japanese: "おやすみなさい", reading: "おやすみなさい", english: "good night" },
  { japanese: "いらっしゃいませ", reading: "いらっしゃいませ", english: "welcome (to a store)" },
  { japanese: "失礼します", reading: "しつれいします", english: "excuse me (leaving)" },
  { japanese: "お久しぶり", reading: "おひさしぶり", english: "long time no see" },
  { japanese: "お元気ですか", reading: "おげんきですか", english: "how are you" },
  { japanese: "わかりました", reading: "わかりました", english: "I understand" },
  { japanese: "いいえ", reading: "いいえ", english: "no" },
  { japanese: "はい", reading: "はい", english: "yes" },
  { japanese: "お大事に", reading: "おだいじに", english: "take care (health)" },
  { japanese: "気をつけて", reading: "きをつけて", english: "take care / be careful" },
  { japanese: "建物", reading: "たてもの", english: "building" },
  { japanese: "花", reading: "はな", english: "flower" },
  { japanese: "犬", reading: "いぬ", english: "dog" },
  { japanese: "猫", reading: "ねこ", english: "cat" },
  { japanese: "鳥", reading: "とり", english: "bird" },
  { japanese: "中", reading: "なか", english: "inside" },
  { japanese: "外", reading: "そと", english: "outside" },
  { japanese: "上", reading: "うえ", english: "above / on" },
  { japanese: "下", reading: "した", english: "below / under" },
  { japanese: "隣", reading: "となり", english: "next to" }
];
