const hiraganaData = [
  { char: "あ", romaji: "a", group: "a-row" },
  { char: "い", romaji: "i", group: "a-row" },
  { char: "う", romaji: "u", group: "a-row" },
  { char: "え", romaji: "e", group: "a-row" },
  { char: "お", romaji: "o", group: "a-row" },
  { char: "か", romaji: "ka", group: "ka-row" },
  { char: "き", romaji: "ki", group: "ka-row" },
  { char: "く", romaji: "ku", group: "ka-row" },
  { char: "け", romaji: "ke", group: "ka-row" },
  { char: "こ", romaji: "ko", group: "ka-row" },
  { char: "さ", romaji: "sa", group: "sa-row" },
  { char: "し", romaji: "shi", group: "sa-row" },
  { char: "す", romaji: "su", group: "sa-row" },
  { char: "せ", romaji: "se", group: "sa-row" },
  { char: "そ", romaji: "so", group: "sa-row" },
  { char: "た", romaji: "ta", group: "ta-row" },
  { char: "ち", romaji: "chi", group: "ta-row" },
  { char: "つ", romaji: "tsu", group: "ta-row" },
  { char: "て", romaji: "te", group: "ta-row" },
  { char: "と", romaji: "to", group: "ta-row" },
  { char: "な", romaji: "na", group: "na-row" },
  { char: "に", romaji: "ni", group: "na-row" },
  { char: "ぬ", romaji: "nu", group: "na-row" },
  { char: "ね", romaji: "ne", group: "na-row" },
  { char: "の", romaji: "no", group: "na-row" },
  { char: "は", romaji: "ha", group: "ha-row" },
  { char: "ひ", romaji: "hi", group: "ha-row" },
  { char: "ふ", romaji: "fu", group: "ha-row" },
  { char: "へ", romaji: "he", group: "ha-row" },
  { char: "ほ", romaji: "ho", group: "ha-row" },
  { char: "ま", romaji: "ma", group: "ma-row" },
  { char: "み", romaji: "mi", group: "ma-row" },
  { char: "む", romaji: "mu", group: "ma-row" },
  { char: "め", romaji: "me", group: "ma-row" },
  { char: "も", romaji: "mo", group: "ma-row" },
  { char: "や", romaji: "ya", group: "ya-row" },
  { char: "ゆ", romaji: "yu", group: "ya-row" },
  { char: "よ", romaji: "yo", group: "ya-row" },
  { char: "ら", romaji: "ra", group: "ra-row" },
  { char: "り", romaji: "ri", group: "ra-row" },
  { char: "る", romaji: "ru", group: "ra-row" },
  { char: "れ", romaji: "re", group: "ra-row" },
  { char: "ろ", romaji: "ro", group: "ra-row" },
  { char: "わ", romaji: "wa", group: "wa-row" },
  { char: "を", romaji: "wo", group: "wa-row" },
  { char: "ん", romaji: "n", group: "n-row" },
  { char: "が", romaji: "ga", group: "ga-row" },
  { char: "ぎ", romaji: "gi", group: "ga-row" },
  { char: "ぐ", romaji: "gu", group: "ga-row" },
  { char: "げ", romaji: "ge", group: "ga-row" },
  { char: "ご", romaji: "go", group: "ga-row" },
  { char: "ざ", romaji: "za", group: "za-row" },
  { char: "じ", romaji: "ji", group: "za-row" },
  { char: "ず", romaji: "zu", group: "za-row" },
  { char: "ぜ", romaji: "ze", group: "za-row" },
  { char: "ぞ", romaji: "zo", group: "za-row" },
  { char: "だ", romaji: "da", group: "da-row" },
  { char: "ぢ", romaji: "ji", group: "da-row" },
  { char: "づ", romaji: "zu", group: "da-row" },
  { char: "で", romaji: "de", group: "da-row" },
  { char: "ど", romaji: "do", group: "da-row" },
  { char: "ば", romaji: "ba", group: "ba-row" },
  { char: "び", romaji: "bi", group: "ba-row" },
  { char: "ぶ", romaji: "bu", group: "ba-row" },
  { char: "べ", romaji: "be", group: "ba-row" },
  { char: "ぼ", romaji: "bo", group: "ba-row" },
  { char: "ぱ", romaji: "pa", group: "pa-row" },
  { char: "ぴ", romaji: "pi", group: "pa-row" },
  { char: "ぷ", romaji: "pu", group: "pa-row" },
  { char: "ぺ", romaji: "pe", group: "pa-row" },
  { char: "ぽ", romaji: "po", group: "pa-row" }
];

const katakanaData = [
  { char: "ア", romaji: "a", group: "a-row" },
  { char: "イ", romaji: "i", group: "a-row" },
  { char: "ウ", romaji: "u", group: "a-row" },
  { char: "エ", romaji: "e", group: "a-row" },
  { char: "オ", romaji: "o", group: "a-row" },
  { char: "カ", romaji: "ka", group: "ka-row" },
  { char: "キ", romaji: "ki", group: "ka-row" },
  { char: "ク", romaji: "ku", group: "ka-row" },
  { char: "ケ", romaji: "ke", group: "ka-row" },
  { char: "コ", romaji: "ko", group: "ka-row" },
  { char: "サ", romaji: "sa", group: "sa-row" },
  { char: "シ", romaji: "shi", group: "sa-row" },
  { char: "ス", romaji: "su", group: "sa-row" },
  { char: "セ", romaji: "se", group: "sa-row" },
  { char: "ソ", romaji: "so", group: "sa-row" },
  { char: "タ", romaji: "ta", group: "ta-row" },
  { char: "チ", romaji: "chi", group: "ta-row" },
  { char: "ツ", romaji: "tsu", group: "ta-row" },
  { char: "テ", romaji: "te", group: "ta-row" },
  { char: "ト", romaji: "to", group: "ta-row" },
  { char: "ナ", romaji: "na", group: "na-row" },
  { char: "ニ", romaji: "ni", group: "na-row" },
  { char: "ヌ", romaji: "nu", group: "na-row" },
  { char: "ネ", romaji: "ne", group: "na-row" },
  { char: "ノ", romaji: "no", group: "na-row" },
  { char: "ハ", romaji: "ha", group: "ha-row" },
  { char: "ヒ", romaji: "hi", group: "ha-row" },
  { char: "フ", romaji: "fu", group: "ha-row" },
  { char: "ヘ", romaji: "he", group: "ha-row" },
  { char: "ホ", romaji: "ho", group: "ha-row" },
  { char: "マ", romaji: "ma", group: "ma-row" },
  { char: "ミ", romaji: "mi", group: "ma-row" },
  { char: "ム", romaji: "mu", group: "ma-row" },
  { char: "メ", romaji: "me", group: "ma-row" },
  { char: "モ", romaji: "mo", group: "ma-row" },
  { char: "ヤ", romaji: "ya", group: "ya-row" },
  { char: "ユ", romaji: "yu", group: "ya-row" },
  { char: "ヨ", romaji: "yo", group: "ya-row" },
  { char: "ラ", romaji: "ra", group: "ra-row" },
  { char: "リ", romaji: "ri", group: "ra-row" },
  { char: "ル", romaji: "ru", group: "ra-row" },
  { char: "レ", romaji: "re", group: "ra-row" },
  { char: "ロ", romaji: "ro", group: "ra-row" },
  { char: "ワ", romaji: "wa", group: "wa-row" },
  { char: "ヲ", romaji: "wo", group: "wa-row" },
  { char: "ン", romaji: "n", group: "n-row" },
  { char: "ガ", romaji: "ga", group: "ga-row" },
  { char: "ギ", romaji: "gi", group: "ga-row" },
  { char: "グ", romaji: "gu", group: "ga-row" },
  { char: "ゲ", romaji: "ge", group: "ga-row" },
  { char: "ゴ", romaji: "go", group: "ga-row" },
  { char: "ザ", romaji: "za", group: "za-row" },
  { char: "ジ", romaji: "ji", group: "za-row" },
  { char: "ズ", romaji: "zu", group: "za-row" },
  { char: "ゼ", romaji: "ze", group: "za-row" },
  { char: "ゾ", romaji: "zo", group: "za-row" },
  { char: "ダ", romaji: "da", group: "da-row" },
  { char: "ヂ", romaji: "ji", group: "da-row" },
  { char: "ヅ", romaji: "zu", group: "da-row" },
  { char: "デ", romaji: "de", group: "da-row" },
  { char: "ド", romaji: "do", group: "da-row" },
  { char: "バ", romaji: "ba", group: "ba-row" },
  { char: "ビ", romaji: "bi", group: "ba-row" },
  { char: "ブ", romaji: "bu", group: "ba-row" },
  { char: "ベ", romaji: "be", group: "ba-row" },
  { char: "ボ", romaji: "bo", group: "ba-row" },
  { char: "パ", romaji: "pa", group: "pa-row" },
  { char: "ピ", romaji: "pi", group: "pa-row" },
  { char: "プ", romaji: "pu", group: "pa-row" },
  { char: "ペ", romaji: "pe", group: "pa-row" },
  { char: "ポ", romaji: "po", group: "pa-row" }
];

const kanjiData = [
  { char: "一", romaji: "ichi", meaning: "one" },
  { char: "二", romaji: "ni", meaning: "two" },
  { char: "三", romaji: "san", meaning: "three" },
  { char: "四", romaji: "shi / yon", meaning: "four" },
  { char: "五", romaji: "go", meaning: "five" },
  { char: "六", romaji: "roku", meaning: "six" },
  { char: "七", romaji: "shichi / nana", meaning: "seven" },
  { char: "八", romaji: "hachi", meaning: "eight" },
  { char: "九", romaji: "kyuu / ku", meaning: "nine" },
  { char: "十", romaji: "juu", meaning: "ten" },
  { char: "百", romaji: "hyaku", meaning: "hundred" },
  { char: "千", romaji: "sen", meaning: "thousand" },
  { char: "万", romaji: "man", meaning: "ten thousand" },
  { char: "円", romaji: "en", meaning: "circle / yen" },
  { char: "日", romaji: "nichi / hi", meaning: "day / sun" },
  { char: "月", romaji: "getsu / tsuki", meaning: "month / moon" },
  { char: "火", romaji: "ka / hi", meaning: "fire" },
  { char: "水", romaji: "sui / mizu", meaning: "water" },
  { char: "木", romaji: "moku / ki", meaning: "tree / wood" },
  { char: "金", romaji: "kin / kane", meaning: "gold / money" },
  { char: "土", romaji: "do / tsuchi", meaning: "earth / soil" },
  { char: "曜", romaji: "you", meaning: "day of week" },
  { char: "年", romaji: "nen / toshi", meaning: "year" },
  { char: "時", romaji: "ji / toki", meaning: "time / hour" },
  { char: "分", romaji: "bun / pun", meaning: "minute / part" },
  { char: "半", romaji: "han", meaning: "half" },
  { char: "上", romaji: "jou / ue", meaning: "above / up" },
  { char: "下", romaji: "ka / shita", meaning: "below / down" },
  { char: "中", romaji: "chuu / naka", meaning: "inside / middle" },
  { char: "大", romaji: "dai / ookii", meaning: "big / large" },
  { char: "小", romaji: "shou / chiisai", meaning: "small / little" },
  { char: "左", romaji: "sa / hidari", meaning: "left" },
  { char: "右", romaji: "u / migi", meaning: "right" },
  { char: "前", romaji: "zen / mae", meaning: "before / front" },
  { char: "後", romaji: "go / ushiro", meaning: "after / behind" },
  { char: "内", romaji: "nai / uchi", meaning: "inside" },
  { char: "外", romaji: "gai / soto", meaning: "outside" },
  { char: "北", romaji: "kita", meaning: "north" },
  { char: "南", romaji: "minami", meaning: "south" },
  { char: "東", romaji: "tou / higashi", meaning: "east" },
  { char: "西", romaji: "sei / nishi", meaning: "west" },
  { char: "入", romaji: "nyuu / hairu", meaning: "enter" },
  { char: "出", romaji: "shutsu / deru", meaning: "exit / leave" },
  { char: "立", romaji: "ritsu / tatsu", meaning: "stand" },
  { char: "休", romaji: "kyuu / yasumu", meaning: "rest" },
  { char: "先", romaji: "sen / saki", meaning: "previous / ahead" },
  { char: "生", romaji: "sei / ikiru", meaning: "life / birth" },
  { char: "学", romaji: "gaku / manabu", meaning: "study / learn" },
  { char: "校", romaji: "kou", meaning: "school" },
  { char: "国", romaji: "koku / kuni", meaning: "country" },
  { char: "語", romaji: "go / kata", meaning: "language" },
  { char: "文", romaji: "bun / fumi", meaning: "writing / sentence" },
  { char: "字", romaji: "ji", meaning: "character / letter" },
  { char: "本", romaji: "hon / moto", meaning: "book / origin" },
  { char: "名", romaji: "mei / na", meaning: "name" },
  { char: "人", romaji: "jin / hito", meaning: "person" },
  { char: "子", romaji: "shi / ko", meaning: "child" },
  { char: "男", romaji: "dan / otoko", meaning: "man / male" },
  { char: "女", romaji: "jo / onna", meaning: "woman / female" },
  { char: "父", romaji: "fu / chichi", meaning: "father" },
  { char: "母", romaji: "bo / haha", meaning: "mother" },
  { char: "友", romaji: "yuu / tomo", meaning: "friend" },
  { char: "私", romaji: "shi / watashi", meaning: "I / me" },
  { char: "今", romaji: "kon / ima", meaning: "now" },
  { char: "何", romaji: "ka / nani", meaning: "what / how many" },
  { char: "度", romaji: "do / tabi", meaning: "degree / time" },
  { char: "毎", romaji: "mai / goto", meaning: "every / each" },
  { char: "週", romaji: "shuu", meaning: "week" },
  { char: "間", romaji: "kan / aida", meaning: "interval / between" },
  { char: "午", romaji: "go", meaning: "noon" },
  { char: "食", romaji: "shoku / taberu", meaning: "eat / food" },
  { char: "飲", romaji: "in / nomu", meaning: "drink" },
  { char: "行", romaji: "kou / iku", meaning: "go" },
  { char: "来", romaji: "rai / kuru", meaning: "come" },
  { char: "帰", romaji: "ki / kaeru", meaning: "return" },
  { char: "見", romaji: "ken / miru", meaning: "see / watch" },
  { char: "聞", romaji: "bun / kiku", meaning: "hear / ask" },
  { char: "話", romaji: "wa / hanasu", meaning: "speak / talk" },
  { char: "読", romaji: "doku / yomu", meaning: "read" },
  { char: "書", romaji: "sho / kaku", meaning: "write" },
  { char: "言", romaji: "gen / iu", meaning: "say / word" },
  { char: "思", romaji: "shi / omou", meaning: "think" },
  { char: "知", romaji: "chi / shiru", meaning: "know" },
  { char: "長", romaji: "chou / nagai", meaning: "long / leader" },
  { char: "白", romaji: "haku / shiroi", meaning: "white" },
  { char: "天", romaji: "ten / ame", meaning: "heaven / sky" },
  { char: "気", romaji: "ki / ke", meaning: "spirit / energy" },
  { char: "多", romaji: "ta / ooi", meaning: "many / much" },
  { char: "少", romaji: "shou / sukunai", meaning: "few / little" },
  { char: "安", romaji: "an / yasui", meaning: "peace / cheap" },
  { char: "新", romaji: "shin / atarashii", meaning: "new" },
  { char: "古", romaji: "ko / furui", meaning: "old" },
  { char: "高", romaji: "kou / takai", meaning: "high / expensive" },
  { char: "買", romaji: "bai / kau", meaning: "buy" },
  { char: "物", romaji: "butsu / mono", meaning: "thing / object" },
  { char: "道", romaji: "dou / michi", meaning: "road / way" },
  { char: "車", romaji: "sha / kuruma", meaning: "car / vehicle" },
  { char: "花", romaji: "ka / hana", meaning: "flower" },
  { char: "林", romaji: "rin / hayashi", meaning: "grove / forest" },
  { char: "森", romaji: "shin / mori", meaning: "forest" }
];

const hiraganaGroups = [
  { key: "a-row", label: "Vowels (a)" },
  { key: "ka-row", label: "K" },
  { key: "sa-row", label: "S" },
  { key: "ta-row", label: "T" },
  { key: "na-row", label: "N" },
  { key: "ha-row", label: "H" },
  { key: "ma-row", label: "M" },
  { key: "ya-row", label: "Y" },
  { key: "ra-row", label: "R" },
  { key: "wa-row", label: "W" },
  { key: "n-row", label: "N (ん)" },
  { key: "ga-row", label: "G (dakuten)" },
  { key: "za-row", label: "Z (dakuten)" },
  { key: "da-row", label: "D (dakuten)" },
  { key: "ba-row", label: "B (dakuten)" },
  { key: "pa-row", label: "P (handakuten)" }
];

const katakanaGroups = [
  { key: "a-row", label: "Vowels (a)" },
  { key: "ka-row", label: "K" },
  { key: "sa-row", label: "S" },
  { key: "ta-row", label: "T" },
  { key: "na-row", label: "N" },
  { key: "ha-row", label: "H" },
  { key: "ma-row", label: "M" },
  { key: "ya-row", label: "Y" },
  { key: "ra-row", label: "R" },
  { key: "wa-row", label: "W" },
  { key: "n-row", label: "N (ン)" },
  { key: "ga-row", label: "G (dakuten)" },
  { key: "za-row", label: "Z (dakuten)" },
  { key: "da-row", label: "D (dakuten)" },
  { key: "ba-row", label: "B (dakuten)" },
  { key: "pa-row", label: "P (handakuten)" }
];
